blank_issues_enabled: false
#contact_links:
#  - name: Discord Support
#    url: discord-link
#    about: For quick help and community support
#  - name: Documentation
#    url: docs-link
#    about: Check our documentation before creating an issue